FROM centos:8
LABEL Author="Evgeniy Naryshkin" Description="Docker Homework - task 8.1"

# install gcc compiler and make util. Clear cache
RUN yum install -y gcc \
    make && \
    gcc --version && \
    rm -rf /var/lib/apt/lists/*

# copy hello.c source file
COPY ./hello.c .

# compile hello.c
RUN make hello && \
    sha256sum ./hello #> sha256-hello-centos

# start hello
CMD [ "./hello" ]
